on:
  push:
    branches:
    - 13-deploy
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: webshop
  CONTAINER_APP_ENVIRONMENT_NAME: mvc-labs
  RESOURCE_GROUP: sandbox-rg
  CONTAINER_REGISTRY_NAME: sandboxlabs
  CONTAINER_REGISTRY_LOGIN_SERVER: sandboxlabs.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.mvc_labs_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.sandboxlabs_USERNAME_78D1 }}
        acrPassword: ${{ secrets.sandboxlabs_PASSWORD_78D1 }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
